"""contact_id

Revision ID: 66bd71037084
Revises: 9b82a7be4eae
Create Date: 2022-10-31 14:26:50.440175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bd71037084'
down_revision = '9b82a7be4eae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_user', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_user', 'chat_user', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_user', type_='foreignkey')
    op.drop_column('chat_user', 'contact_id')
    # ### end Alembic commands ###
