"""message_created

Revision ID: 9b82a7be4eae
Revises: ca2bef55e424
Create Date: 2022-10-26 10:59:14.955875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b82a7be4eae'
down_revision = 'ca2bef55e424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'created_at')
    # ### end Alembic commands ###
