"""roles

Revision ID: ca2bef55e424
Revises: b39431a5972a
Create Date: 2022-10-25 15:49:08.877619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2bef55e424'
down_revision = 'b39431a5972a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_user', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('chat_user', sa.Column('role_name', sa.String(length=10), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_user', 'role_name')
    op.drop_column('chat_user', 'is_active')
    # ### end Alembic commands ###
