"""roles

Revision ID: f7c94ef05b41
Revises: b39431a5972a
Create Date: 2022-10-21 13:19:43.250635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c94ef05b41'
down_revision = 'b39431a5972a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_user', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('chat_user', sa.Column('role_name', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_user', 'role_name')
    op.drop_column('chat_user', 'active')
    # ### end Alembic commands ###
